"""Markdown document writer."""

from datetime import datetime
from pathlib import Path

from ai_writer.models.paper import Paper


class MarkdownWriter:
    """Writer for exporting papers to Markdown format."""

    def write(self, path: Path | str, content: str | Paper) -> Path:
        """Write content to a Markdown file.

        Args:
            path: Path where to save the file.
            content: Either a Paper object or raw markdown string.

        Returns:
            Path to the created file.
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)

        if isinstance(content, Paper):
            markdown_content = self._generate_markdown(content)
        else:
            markdown_content = content

        path.write_text(markdown_content, encoding="utf-8")

        return path

    def write_paper(self, paper: Paper, path: Path | str) -> Path:
        """Write a paper to a Markdown file (legacy method).

        Args:
            paper: The paper to export.
            path: Path where to save the file.

        Returns:
            Path to the created file.
        """
        return self.write(path, paper)

        return path

    def to_string(self, paper: Paper) -> str:
        """Convert a paper to Markdown string.

        Args:
            paper: The paper to convert.

        Returns:
            Markdown formatted string.
        """
        return self._generate_markdown(paper)

    def _generate_markdown(self, paper: Paper) -> str:
        """Generate Markdown content from a paper.

        Args:
            paper: The paper to convert.

        Returns:
            Markdown formatted content.
        """
        lines = []

        # Title
        lines.append(f"# {paper.title}")
        lines.append("")

        # Authors
        if paper.authors:
            authors_str = ", ".join(paper.authors)
            lines.append(f"**Authors:** {authors_str}")
            lines.append("")

        # Date
        lines.append(f"**Date:** {datetime.now().strftime('%B %d, %Y')}")
        lines.append("")

        # Keywords
        if paper.keywords:
            keywords_str = ", ".join(paper.keywords)
            lines.append(f"**Keywords:** {keywords_str}")
            lines.append("")

        # Horizontal rule
        lines.append("---")
        lines.append("")

        # Table of Contents
        lines.append("## Table of Contents")
        lines.append("")
        for i, section in enumerate(paper.sections, 1):
            # Create anchor-friendly slug
            slug = section.title.lower().replace(" ", "-")
            lines.append(f"{i}. [{section.title}](#{slug})")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Sections
        for section in paper.sections:
            lines.append(f"## {section.title}")
            lines.append("")
            lines.append(section.content)
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by TheAIWriter*")

        return "\n".join(lines)
